[workspace]
resolver = "2"

members = [
    "crates/walk_imports",
    "crates/reporter",
    "crates/es_resolver",
    "crates/web_server",
    "crates/fetch_and_report",
    "crates/esm_checker_bindings",
    "crates/report_model"
]

[profile.release]
lto = true
strip = "symbols"
