/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface WithCommonJsDependencies {
  packageName: string
  transitiveCommonjsDependencies: Array<string>
}
export interface WithMissingJsFileExtensions {
  packageName: string
  transitiveDepsWithMissingJsFileExtensions: Array<string>
}
export interface FauxEsm {
  withCommonjsDependencies: Array<WithCommonJsDependencies>
  withMissingJsFileExtensions: Array<WithMissingJsFileExtensions>
}
export interface ResolveError {
  packageName: string
  from: string
  importSpecifier: string
  originalErrorMessage: string
}
export interface ParseError {
  packageName: string
  path: string
  originalErrorMessage: string
}
export interface Report {
  total: number
  esm: Array<string>
  cjs: Array<string>
  fauxEsm: FauxEsm
  resolveErrors: Array<ResolveError>
  parseErrors: Array<ParseError>
}
export declare function generateReport(packageJsonLocation: string, check?: Array<string> | undefined | null): Report
