name: CI
env:
  DEBUG: napi:*
  APP_NAME: checker
  MACOSX_DEPLOYMENT_TARGET: '10.13'
permissions:
  contents: write
  id-token: write
'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
            build: corepack yarn build --target aarch64-apple-darwin
          - host: macos-latest
            target: x86_64-apple-darwin
            build: corepack yarn build --target x86_64-apple-darwin
          - host: windows-latest
            build: corepack yarn build --target x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
            build: yarn build --target x86_64-unknown-linux-gnu
    name: stable - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        working-directory: ${{ github.workspace }}/crates/napi_esm
        # corepack enable fails on windows.
        run: npm i -g --force corepack && corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        if: ${{ !matrix.settings.docker }}
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: ${{ github.workspace }}/crates/napi_esm
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}
      - uses: goto-bus-stop/setup-zig@v2
        if: ${{ matrix.settings.target == 'armv7-unknown-linux-gnueabihf' || matrix.settings.target == 'armv7-unknown-linux-musleabihf' }}
        with:
          version: 0.13.0
      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash
      - name: Build in docker
        uses: addnab/docker-run-action@v3
        if: ${{ matrix.settings.docker }}
        with:
          image: ${{ matrix.settings.docker }}
          options: '--user 0:0 -v ${{ github.workspace }}/.cargo-cache/git/db:/usr/local/cargo/git/db -v ${{ github.workspace }}/.cargo/registry/cache:/usr/local/cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/usr/local/cargo/registry/index -v ${{ github.workspace }}:/build -w /build'
          # cd relpath because we are inside docker
          run: |
            cd ./crates/napi_esm
            ${{ matrix.settings.build }}
      - name: Build
        working-directory: ${{ github.workspace }}/crates/napi_esm
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ github.workspace }}/crates/napi_esm/${{ env.APP_NAME }}.*.node
          if-no-files-found: error
  test-macOS-windows-binding:
    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
        node:
          - '20'
          - '22'
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        working-directory: ${{ github.workspace }}/crates/napi_esm
        # corepack enable fails on windows.
        run: npm i -g --force corepack && corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          architecture: x64
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: ${{ github.workspace }}/crates/napi_esm
      - name: Install dependencies
        working-directory: ./crates/napi_esm
        run: yarn install
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: ${{ github.workspace }}/crates/napi_esm
      - name: List packages
        working-directory: ./crates/napi_esm
        run: ls -R .
        shell: bash
      - name: Test bindings
        working-directory: ./crates/napi_esm
        run: node --test
  test-linux-x64-gnu-binding:
    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node:
          - '20'
          - '22'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        working-directory: ${{ github.workspace }}/crates/napi_esm
        # corepack enable fails on windows.
        run: npm i -g --force corepack && corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: ${{ github.workspace }}/crates/napi_esm
      - name: Install dependencies
        working-directory: ./crates/napi_esm
        run: yarn install
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-unknown-linux-gnu
          path: ${{ github.workspace }}/crates/napi_esm
      - name: List packages
        working-directory: ./crates/napi_esm
        run: ls -R .
        shell: bash
      - name: Debug
        run: |
          ls
          echo "......"
          ls ./crates/napi_esm
        shell: bash
      - name: Test bindings
        run: docker run --rm -v $(pwd):/build -w /build node:${{ matrix.node }}-slim /bin/bash -c "cd ./crates/napi_esm && node --test"
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - test-macOS-windows-binding
      - test-linux-x64-gnu-binding
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        working-directory: ${{ github.workspace }}/crates/napi_esm
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: ${{ github.workspace }}/crates/napi_esm
      - name: Install dependencies
        working-directory: ./crates/napi_esm
        run: yarn install
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./crates/napi_esm/artifacts
      - name: Move artifacts
        working-directory: ./crates/napi_esm
        run: yarn artifacts
      - name: List packages
        working-directory: ./crates/napi_esm
        run: ls -R ./npm
        shell: bash
      - name: Install napi globally
        working-directory: ./crates/napi_esm
        run: npm i -g --force @napi-rs/cli
        shell: bash
      - name: Publish
        working-directory: ./crates/napi_esm
        # if: major.minor.patch
        # elif: major.minor.patch-next (or patch.x or anything else after patch)
        run: |
          ls
          npm config set provenance true
          if git log -1 --pretty=%B | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish --access public
          elif git log -1 --pretty=%B | grep -E "^[0-9]+\.[0-9]+\.[0-9]+";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish --tag next --access public
          else
            echo "Not a release, skipping publish"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
